# Generated by Django 4.1.3 on 2022-11-29 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_user_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='scope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='event.eventscope'),
        ),
    ]
